services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
      - ./shared:/data/shared
    networks:
      - n8n-network
    environment:
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
      - N8N_RESTRICT_FILE_ACCESS_TO=/data/shared

  browserless:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    networks:
      - n8n-network
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - PREBOOT_CHROME=true

  ollama:
    build:
      context: docker/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    networks:
      - n8n-network
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - MODELS=nomic-embed-text
      - OLLAMA_HOST=0.0.0.0:11434


networks:
  n8n-network:
    driver: bridge


volumes:
  n8n-data:
    driver: local
  ollama-data:
    driver: local

